---
# Source: mysql-kubernetes/templates/networkpolicy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-workload-ingress
spec:
  podSelector:
    matchLabels:
      mysql.oracle.com/cluster: mysql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
    - namespaceSelector:
        matchLabels:
          platform-access: 'true'
---
# Source: mysql-kubernetes/templates/cluster.yaml
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql
spec:
  datadirVolumeClaimTemplate:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  instances: 3
  podSpec:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              component: mysqld
              mysql.oracle.com/cluster: mysql
          topologyKey: kubernetes.io/hostname
    containers:
    - name: mysql
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: 250m
          memory: 512Mi
  router:
    instances: 2
    podSpec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                component: mysqlrouter
                mysql.oracle.com/cluster: mysql
            topologyKey: kubernetes.io/hostname
      containers:
      - name: router
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
    version: 26.7.0
  secretName: mysql-credentials
  tlsUseSelfSigned: true
  version: 8.4.12
